language: android
jdk: oraclejdk8
os:
  - linux
env:
  global:
    - ANDROID_API_LEVEL=30
    - EMULATOR_API_LEVEL=23
    - ANDROID_BUILD_TOOLS_VERSION=30.0.3
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=20
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
script:
  - ./gradlew clean build lint test assembleAndroidTest
  - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)