language: android
dist: trusty
jdk: oraclejdk8
os:
  - linux
git:
  depth: false
  submodules: false
android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-30
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-30
script: 
  - "sudo ./gradlew build connectedCheck --stacktrace"
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 9166c3b5-d71b-4714-95aa-3fd6811d59dc